GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Ödevlerini Yap"
}

###

DELETE http://localhost:3001/todo/delete/642efdcc8382c359c9b9fa4c

###

PUT http://localhost:3001/todo/complete/642eff3e811b30e4a80dc88f